### ISSUE TITLE
[Bug] Set minimum width for the arcs in the pie chart

### ISSUE THREAD

**Issue by getwithashish** [getwithashish/ExAM#386]
**Describe the bug**
The arcs in the pie chart is being shown according to the count of the asset. If the count is too low, the corresponding arc is very small and therefore, user cannot select that arc.

**To Reproduce**
1. Hover over the Chart
2. Identify the smallest arc
3. Try to click on the smallest arc

**Expected behavior**
All the arcs must be clearly visible and clickable to the users, no matter how small their size is.

**Screenshots**
![image](https://github.com/user-attachments/assets/173d929f-5a9b-4bcb-87da-1fbef36419c6)
Here, this arc is too small and very hard to click on.

**Additional context**
Possible solutions:
- Set a minimum width for the arcs.

**Comment by AidrinVarghese** [comment]
As of now there is no slot prop to set a min angle width for pie arc. Will check for updates
