### ISSUE TITLE
[Bug] Application crash on approval of asset modification

### ISSUE THREAD

**Issue by getwithashish** [getwithashish/ExAM#393]
**Describe the bug**
When opening the request for Asset Modification, the entire application crashes.

**To Reproduce**
1. Login as System Admin
2. Modify an existing asset
3. Login as Lead
4. Go to "Approve Assets" -> "In Modification"
5. Click on the View icon of an asset

**Expected behavior**
When the view icon of the asset is clicked, it should show the details of the asset along with highlighting the modified fields.

**Additional Context**
- This may be due to the logs not being created when the assets are imported.

**Comment by Ananthan1CJ** [comment]
Asset logs wil be created along with bulk create and hence it will not happen again.

**Comment by getwithashish** [comment]
Noted.

**Comment by getwithashish** [comment]
Problems to Solve:

- [ ] Not all logs are being created, Currently only 719 logs are created out of 2960.
`select * from asset_asset`
![image](https://github.com/user-attachments/assets/e3b271a1-4e98-42d0-95bb-337cb9e691d6)
`select * from asset_assetlog`
![image](https://github.com/user-attachments/assets/1cd13351-f155-49a6-b5da-3c78edd395b1)

**Comment by getwithashish** [comment]
Fixed by #427
