### ISSUE TITLE
[Feature] Add Advanced Search in Modify, Allocate, Deallocate Pages

### ISSUE THREAD

**Issue by getwithashish** [getwithashish/ExAM#443]
**Is your feature request related to a problem? Please describe.**
As a user, I am not able to perform advanced search in modify, allocate and deallocate pages.

**Describe the solution you'd like**
As a user, I want advanced search in modify, allocate and deallocate pages.

**Comment by AidrinVarghese** [comment]
So it means advanced query search should be present in all these three pages?

**Comment by getwithashish** [comment]
Right
